# =============================================================================
# Boulder Dash style menu graphics (full size editor)
# =============================================================================

# -----------------------------------------------------------------------------
# viewport definitions
# -----------------------------------------------------------------------------

# custom window size
viewport.window.EDITOR.width:			784
viewport.window.EDITOR.height:			480

# custom screen sizes and positions
viewport.playfield.EDITOR.width:		684
viewport.playfield.EDITOR.height:		480

# custom door panel sizes and positions
viewport.door_1.EDITOR.x:			684
viewport.door_1.EDITOR.y:			0
viewport.door_1.EDITOR.width:			100
viewport.door_1.EDITOR.height:			326

viewport.door_2.EDITOR.x:			684
viewport.door_2.EDITOR.y:			336
viewport.door_2.EDITOR.width:			100
viewport.door_2.EDITOR.height:			144
