# =============================================================================
# Boulder Dash style graphics
# =============================================================================

name:					Boulder Dash (Full Size Editor)


# -----------------------------------------------------------------------------
# include all required definitions
# -----------------------------------------------------------------------------

include:				gic_menu.conf
include:				gic_menu_editor.conf
include:				gic_game.conf
include:				gic_char.conf
